# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/josh/superfx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/josh/superfx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/josh/superfx/CMakeFiles /home/josh/superfx/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/josh/superfx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named superfx

# Build rule for target.
superfx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 superfx
.PHONY : superfx

# fast build rule for target.
superfx/fast:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/build
.PHONY : superfx/fast

bind.o: bind.c.o

.PHONY : bind.o

# target to build an object file
bind.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/bind.c.o
.PHONY : bind.c.o

bind.i: bind.c.i

.PHONY : bind.i

# target to preprocess a source file
bind.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/bind.c.i
.PHONY : bind.c.i

bind.s: bind.c.s

.PHONY : bind.s

# target to generate assembly for a file
bind.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/bind.c.s
.PHONY : bind.c.s

console.o: console.c.o

.PHONY : console.o

# target to build an object file
console.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/console.c.o
.PHONY : console.c.o

console.i: console.c.i

.PHONY : console.i

# target to preprocess a source file
console.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/console.c.i
.PHONY : console.c.i

console.s: console.c.s

.PHONY : console.s

# target to generate assembly for a file
console.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/console.c.s
.PHONY : console.c.s

parse.o: parse.c.o

.PHONY : parse.o

# target to build an object file
parse.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/parse.c.o
.PHONY : parse.c.o

parse.i: parse.c.i

.PHONY : parse.i

# target to preprocess a source file
parse.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/parse.c.i
.PHONY : parse.c.i

parse.s: parse.c.s

.PHONY : parse.s

# target to generate assembly for a file
parse.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/parse.c.s
.PHONY : parse.c.s

superfx.o: superfx.c.o

.PHONY : superfx.o

# target to build an object file
superfx.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/superfx.c.o
.PHONY : superfx.c.o

superfx.i: superfx.c.i

.PHONY : superfx.i

# target to preprocess a source file
superfx.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/superfx.c.i
.PHONY : superfx.c.i

superfx.s: superfx.c.s

.PHONY : superfx.s

# target to generate assembly for a file
superfx.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/superfx.c.s
.PHONY : superfx.c.s

superfx_wrap.o: superfx_wrap.c.o

.PHONY : superfx_wrap.o

# target to build an object file
superfx_wrap.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/superfx_wrap.c.o
.PHONY : superfx_wrap.c.o

superfx_wrap.i: superfx_wrap.c.i

.PHONY : superfx_wrap.i

# target to preprocess a source file
superfx_wrap.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/superfx_wrap.c.i
.PHONY : superfx_wrap.c.i

superfx_wrap.s: superfx_wrap.c.s

.PHONY : superfx_wrap.s

# target to generate assembly for a file
superfx_wrap.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/superfx_wrap.c.s
.PHONY : superfx_wrap.c.s

text.o: text.c.o

.PHONY : text.o

# target to build an object file
text.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/text.c.o
.PHONY : text.c.o

text.i: text.c.i

.PHONY : text.i

# target to preprocess a source file
text.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/text.c.i
.PHONY : text.c.i

text.s: text.c.s

.PHONY : text.s

# target to generate assembly for a file
text.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/text.c.s
.PHONY : text.c.s

tritri.o: tritri.c.o

.PHONY : tritri.o

# target to build an object file
tritri.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/tritri.c.o
.PHONY : tritri.c.o

tritri.i: tritri.c.i

.PHONY : tritri.i

# target to preprocess a source file
tritri.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/tritri.c.i
.PHONY : tritri.c.i

tritri.s: tritri.c.s

.PHONY : tritri.s

# target to generate assembly for a file
tritri.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/tritri.c.s
.PHONY : tritri.c.s

utils.o: utils.c.o

.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i

.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s

.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/utils.c.s
.PHONY : utils.c.s

writepng.o: writepng.c.o

.PHONY : writepng.o

# target to build an object file
writepng.c.o:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/writepng.c.o
.PHONY : writepng.c.o

writepng.i: writepng.c.i

.PHONY : writepng.i

# target to preprocess a source file
writepng.c.i:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/writepng.c.i
.PHONY : writepng.c.i

writepng.s: writepng.c.s

.PHONY : writepng.s

# target to generate assembly for a file
writepng.c.s:
	$(MAKE) -f CMakeFiles/superfx.dir/build.make CMakeFiles/superfx.dir/writepng.c.s
.PHONY : writepng.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... superfx"
	@echo "... bind.o"
	@echo "... bind.i"
	@echo "... bind.s"
	@echo "... console.o"
	@echo "... console.i"
	@echo "... console.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... superfx.o"
	@echo "... superfx.i"
	@echo "... superfx.s"
	@echo "... superfx_wrap.o"
	@echo "... superfx_wrap.i"
	@echo "... superfx_wrap.s"
	@echo "... text.o"
	@echo "... text.i"
	@echo "... text.s"
	@echo "... tritri.o"
	@echo "... tritri.i"
	@echo "... tritri.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... writepng.o"
	@echo "... writepng.i"
	@echo "... writepng.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

